services:
  db:
    image: postgres:16-alpine
    container_name: swapi_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: swapi
      POSTGRES_PASSWORD: swapi
      POSTGRES_DB: swapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
